//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminSoftPF.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdminSoftPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap address_directory_phonebook_contact_book_contact_list_icon_262944 {
            get {
                object obj = ResourceManager.GetObject("address_directory_phonebook_contact_book_contact_list_icon_262944", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap address_directory_phonebook_contact_book_contact_list_icon_2629441 {
            get {
                object obj = ResourceManager.GetObject("address_directory_phonebook_contact_book_contact_list_icon_2629441", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap analysis_research_example_case_study_icon_262980 {
            get {
                object obj = ResourceManager.GetObject("analysis_research_example_case_study_icon_262980", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap analysis_research_example_case_study_icon_2629801 {
            get {
                object obj = ResourceManager.GetObject("analysis_research_example_case_study_icon_2629801", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cv_resume_curriculum_vitae_qualifications_employment_history_icon_262945 {
            get {
                object obj = ResourceManager.GetObject("cv_resume_curriculum_vitae_qualifications_employment_history_icon_262945", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cv_resume_curriculum_vitae_qualifications_employment_history_icon_2629451 {
            get {
                object obj = ResourceManager.GetObject("cv_resume_curriculum_vitae_qualifications_employment_history_icon_2629451", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap female_entrepreneur_business_business_women_professional_woman_icon_262979 {
            get {
                object obj = ResourceManager.GetObject("female_entrepreneur_business_business_women_professional_woman_icon_262979", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap female_entrepreneur_business_business_women_professional_woman_icon_2629791 {
            get {
                object obj = ResourceManager.GetObject("female_entrepreneur_business_business_women_professional_woman_icon_2629791", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap guidance_coaching_mentorship_leadership_personal_direction_icon_262924 {
            get {
                object obj = ResourceManager.GetObject("guidance_coaching_mentorship_leadership_personal_direction_icon_262924", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap guidance_coaching_mentorship_leadership_personal_direction_icon_2629241 {
            get {
                object obj = ResourceManager.GetObject("guidance_coaching_mentorship_leadership_personal_direction_icon_2629241", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icono {
            get {
                object obj = ResourceManager.GetObject("icono", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap impresora {
            get {
                object obj = ResourceManager.GetObject("impresora", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap impresora1 {
            get {
                object obj = ResourceManager.GetObject("impresora1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap income_earnings_revenue_salary_profit_icon_262952 {
            get {
                object obj = ResourceManager.GetObject("income_earnings_revenue_salary_profit_icon_262952", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap income_earnings_revenue_salary_profit_icon_2629521 {
            get {
                object obj = ResourceManager.GetObject("income_earnings_revenue_salary_profit_icon_2629521", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap interview_employment_hiring_job_interview_recruitment_process_candidate_assessment_icon_262922 {
            get {
                object obj = ResourceManager.GetObject("interview_employment_hiring_job_interview_recruitment_process_candidate_assessmen" +
                        "t_icon_262922", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap interview_employment_hiring_job_interview_recruitment_process_candidate_assessment_icon_2629221 {
            get {
                object obj = ResourceManager.GetObject("interview_employment_hiring_job_interview_recruitment_process_candidate_assessmen" +
                        "t_icon_2629221", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap invoice_bill_payment_request_billing_statement_financial_document_icon_262954 {
            get {
                object obj = ResourceManager.GetObject("invoice_bill_payment_request_billing_statement_financial_document_icon_262954", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap invoice_bill_payment_request_billing_statement_financial_document_icon_2629541 {
            get {
                object obj = ResourceManager.GetObject("invoice_bill_payment_request_billing_statement_financial_document_icon_2629541", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LOG {
            get {
                object obj = ResourceManager.GetObject("LOG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LOG1 {
            get {
                object obj = ResourceManager.GetObject("LOG1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap management_leadership_administration_supervision_oversight_icon_262956 {
            get {
                object obj = ResourceManager.GetObject("management_leadership_administration_supervision_oversight_icon_262956", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap management_leadership_administration_supervision_oversight_icon_2629561 {
            get {
                object obj = ResourceManager.GetObject("management_leadership_administration_supervision_oversight_icon_2629561", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap networking_connections_contacts_relationships_networking_icon_262999 {
            get {
                object obj = ResourceManager.GetObject("networking_connections_contacts_relationships_networking_icon_262999", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap networking_connections_contacts_relationships_networking_icon_2629991 {
            get {
                object obj = ResourceManager.GetObject("networking_connections_contacts_relationships_networking_icon_2629991", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap picking_select_member_team_selection_user_choice_icon_262968 {
            get {
                object obj = ResourceManager.GetObject("picking_select_member_team_selection_user_choice_icon_262968", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap picking_select_member_team_selection_user_choice_icon_2629681 {
            get {
                object obj = ResourceManager.GetObject("picking_select_member_team_selection_user_choice_icon_2629681", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap professional_executive_entrepreneur_business_man_icon_262974 {
            get {
                object obj = ResourceManager.GetObject("professional_executive_entrepreneur_business_man_icon_262974", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap professional_executive_entrepreneur_business_man_icon_2629741 {
            get {
                object obj = ResourceManager.GetObject("professional_executive_entrepreneur_business_man_icon_2629741", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap promotion_advertising_campaign_email_email_marketing_icon_262989 {
            get {
                object obj = ResourceManager.GetObject("promotion_advertising_campaign_email_email_marketing_icon_262989", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap promotion_advertising_campaign_email_email_marketing_icon_2629891 {
            get {
                object obj = ResourceManager.GetObject("promotion_advertising_campaign_email_email_marketing_icon_2629891", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap security_precaution_safety_protection_risk_management_icon_263006 {
            get {
                object obj = ResourceManager.GetObject("security_precaution_safety_protection_risk_management_icon_263006", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap security_precaution_safety_protection_risk_management_icon_2630061 {
            get {
                object obj = ResourceManager.GetObject("security_precaution_safety_protection_risk_management_icon_2630061", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
